on:
  push:
  schedule:
    - cron:  '*/15 * * * *'
name: Test
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: SAP/project-piper-action@master
      with:
        command: help
    - uses: SAP/project-piper-action@master
      with:
        command: version
        flags: -v
    - uses: SAP/project-piper-action@master
      with:
        command: karmaExecuteTests
