on:
  push:
    branches: "**"
  schedule:
    - cron:  '0 6 * * *'
name: Test
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: SAP/project-piper-action@master
      with:
        command: help
    - uses: SAP/project-piper-action@master
      with:
        command: version
        flags: -v
    - uses: SAP/project-piper-action@master
      with:
        command: karmaExecuteTests
    - uses: SAP/project-piper-action@master
      with:
        command: karmaExecuteTests
        piper-version: master
    - uses: SAP/project-piper-action@master
      with:
        command: karmaExecuteTests
        piper-version: v1.14.0
